CREATE TABLE student(id BIGINT PRIMARY KEY AUTO_INCREMENT,
    firstname VARCHAR(100), surname VARCHAR(100), major VARCHAR(200));
    
CREATE TABLE user(id BIGINT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(60), password VARCHAR(60), name VARCHAR(50), email VARCHAR(50));